# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - bioc-devel
  - bioc-release
  - release
  - devel
r_packages:
  - covr
before_install:
    - sudo apt-get -qq update
    - Rscript -e 'install.packages("devtools"); install_github("hadley/testthat")'
after_success:
  - Rscript -e 'library(covr); codecov()'
sudo: true
cache: packages
notifications:
  slack:
    rooms:
      - svn-group:WwFD9sJdhbUOPdCX9WA329BL#travis-ci
  email:
    on_success: always
    recipients:
      - andrewrech@gmail.com