# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - bioc-devel
  - bioc-release
  - release
  - devel
  - 3.4.0
env:
  - MC_CORES=2 OMP_NUM_THREADS=2 DISPLAY=:1
warnings_are_errors: false
r_check_args: ""
cache: packages
before_install:
    - sudo apt-get install -y libv8-3.14-dev ghostscript libgs-dev
    - Rscript -e 'install.packages("devtools"); devtools::install_github("hadley/devtools"); install.packages("testthat")'
sudo: true
repos:
  CRAN: https://cloud.r-project.org
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
cache: packages
notifications:
  email:
    on_success: always
    recipients:
      - andrewrech@gmail.com
